wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.5
    code_path: code/forecast-with-cnn-wandb.py
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.7
    session_history: code/_session_history.ipynb
batch_size:
  desc: null
  value: 6
dropout:
  desc: null
  value: 0.2
epochs:
  desc: null
  value: 90
